### PR TITLE
Makes it compatible with Jupyter Lab 4

### LINKED ISSUE #40: Not compatible with Jupyter Lab 4
When installing the theme in Jupyter Lab 4, it downgrades to Jupyter Lab 3.

### PR DESCRIPTION
**Pull request by gabrielmagno**
Fixes #40

### CODE REVIEW

**Comment by danielcs88** [comment]
Hi @gabrielmagno I'm experiencing the following error

```
Processing /Users/daniel/Downloads/dracula-jupyterlab
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting jupyterlab==3.*,>=3.0.0rc13 (from JLDracula==0.1.0)
  Using cached jupyterlab-3.6.6-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: ipython in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (8.16.1)
Requirement already satisfied: packaging in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (23.2)
Requirement already satisfied: tornado>=6.1.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (6.3.3)
Requirement already satisfied: jupyter-core in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (5.4.0)
Requirement already satisfied: jupyterlab-server~=2.19 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.25.0)
Requirement already satisfied: jupyter-server<3,>=1.16.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.8.0)
Collecting jupyter-ydoc~=0.2.4 (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached jupyter_ydoc-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting jupyter-server-ydoc~=0.8.0 (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached jupyter_server_ydoc-0.8.0-py3-none-any.whl (11 kB)
Collecting nbclassic (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached nbclassic-1.0.0-py3-none-any.whl (10.0 MB)
Collecting notebook<7 (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached notebook-6.5.6-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: jinja2>=2.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (3.1.2)
Requirement already satisfied: tomli in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jinja2>=2.1->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.1.3)
Requirement already satisfied: anyio>=3.1.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (4.0.0)
Requirement already satisfied: argon2-cffi in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (23.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (8.4.0)
Requirement already satisfied: jupyter-events>=0.6.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.8.0)
Requirement already satisfied: jupyter-server-terminals in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (7.9.2)
Requirement already satisfied: nbformat>=5.3.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (5.9.2)
Requirement already satisfied: overrides in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (7.4.0)
Requirement already satisfied: prometheus-client in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.17.1)
Requirement already satisfied: pyzmq>=24 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (25.1.1)
Requirement already satisfied: send2trash>=1.8.2 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.17.1)
Requirement already satisfied: traitlets>=5.6.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (5.11.2)
Requirement already satisfied: websocket-client in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.6.4)
Requirement already satisfied: platformdirs>=2.5 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (3.11.0)
Collecting jupyter-server-fileid<1,>=0.6.0 (from jupyter-server-ydoc~=0.8.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached jupyter_server_fileid-0.9.0-py3-none-any.whl (15 kB)
Collecting ypy-websocket<0.9.0,>=0.8.2 (from jupyter-server-ydoc~=0.8.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached ypy_websocket-0.8.4-py3-none-any.whl (10 kB)
Collecting y-py<0.7.0,>=0.6.0 (from jupyter-ydoc~=0.2.4->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached y_py-0.6.2-cp310-cp310-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl.metadata (5.6 kB)
Requirement already satisfied: babel>=2.10 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.13.0)
Requirement already satisfied: json5>=0.9.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.9.14)
Requirement already satisfied: jsonschema>=4.18.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (4.19.1)
Requirement already satisfied: requests>=2.31 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.31.0)
Collecting pyzmq>=24 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached pyzmq-24.0.1-cp310-cp310-macosx_10_15_universal2.whl (1.8 MB)
Collecting jupyter-client>=7.4.4 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached jupyter_client-7.4.9-py3-none-any.whl (133 kB)
Requirement already satisfied: ipython-genutils in /Users/daniel/miniforge3/lib/python3.10/site-packages (from notebook<7->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.2.0)
Requirement already satisfied: nest-asyncio>=1.5 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from notebook<7->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.5.8)
Requirement already satisfied: ipykernel in /Users/daniel/miniforge3/lib/python3.10/site-packages (from notebook<7->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (6.25.2)
Requirement already satisfied: notebook-shim>=0.2.3 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbclassic->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.2.3)
Requirement already satisfied: backcall in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.2.0)
Requirement already satisfied: decorator in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.1.6)
Requirement already satisfied: pickleshare in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.16.1)
Requirement already satisfied: stack-data in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.6.2)
Requirement already satisfied: exceptiongroup in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.1.3)
Requirement already satisfied: pexpect>4.3 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (4.8.0)
Requirement already satisfied: appnope in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.1.3)
Requirement already satisfied: idna>=2.8 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from anyio>=3.1.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (3.4)
Requirement already satisfied: sniffio>=1.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from anyio>=3.1.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jedi>=0.16->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.8.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.10.6)
Requirement already satisfied: entrypoints in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.8.2)
Requirement already satisfied: python-json-logger>=2.0.4 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (6.0.1)
Requirement already satisfied: rfc3339-validator in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.1.1)
Requirement already satisfied: beautifulsoup4 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (4.12.2)
Requirement already satisfied: bleach!=5.0.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (6.1.0)
Requirement already satisfied: defusedxml in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.2.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (3.0.1)
Requirement already satisfied: nbclient>=0.5.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.5.0)
Requirement already satisfied: tinycss2 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.2.1)
Requirement already satisfied: fastjsonschema in /Users/daniel/miniforge3/lib/python3.10/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.18.1)
Requirement already satisfied: ptyprocess>=0.5 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from pexpect>4.3->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.7.0)
Requirement already satisfied: wcwidth in /Users/daniel/miniforge3/lib/python3.10/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.2.8)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (3.3.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server~=2.19->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2023.7.22)
Collecting aiofiles<23,>=22.1.0 (from ypy-websocket<0.9.0,>=0.8.2->jupyter-server-ydoc~=0.8.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached aiofiles-22.1.0-py3-none-any.whl (14 kB)
Collecting aiosqlite<1,>=0.17.0 (from ypy-websocket<0.9.0,>=0.8.2->jupyter-server-ydoc~=0.8.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0)
  Using cached aiosqlite-0.19.0-py3-none-any.whl (15 kB)
Requirement already satisfied: argon2-cffi-bindings in /Users/daniel/miniforge3/lib/python3.10/site-packages (from argon2-cffi->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (21.2.0)
Requirement already satisfied: comm>=0.1.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipykernel->notebook<7->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipykernel->notebook<7->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.8.0)
Requirement already satisfied: psutil in /Users/daniel/miniforge3/lib/python3.10/site-packages (from ipykernel->notebook<7->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (5.9.5)
Requirement already satisfied: executing>=1.2.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from stack-data->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from stack-data->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.4.0)
Requirement already satisfied: pure-eval in /Users/daniel/miniforge3/lib/python3.10/site-packages (from stack-data->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.16.0)
Requirement already satisfied: webencodings in /Users/daniel/miniforge3/lib/python3.10/site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (0.5.1)
Requirement already satisfied: fqdn in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.5.1)
Requirement already satisfied: isoduration in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.4)
Requirement already satisfied: uri-template in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.3.0)
Requirement already satisfied: webcolors>=1.11 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.13)
Requirement already satisfied: cffi>=1.0.1 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.5)
Requirement already satisfied: pycparser in /Users/daniel/miniforge3/lib/python3.10/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.21)
Requirement already satisfied: arrow>=0.15.0 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /Users/daniel/miniforge3/lib/python3.10/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0rc13->JLDracula==0.1.0) (2.8.19.14)
Using cached jupyterlab-3.6.6-py3-none-any.whl (8.9 MB)
Using cached jupyter_ydoc-0.2.5-py3-none-any.whl (6.2 kB)
Using cached notebook-6.5.6-py3-none-any.whl (529 kB)
Using cached y_py-0.6.2-cp310-cp310-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl (1.5 MB)
Building wheels for collected packages: JLDracula
  Building wheel for JLDracula (pyproject.toml): started
  Building wheel for JLDracula (pyproject.toml): finished with status 'error'
Failed to build JLDracula

```

**Comment by gabrielmagno** [comment]
Hi @danielcs88 . I've updated the pyproject.toml file to use more recent version of the build packages.

Could you please test it again? Make sure to install from the correct branch:
```
pip install git+https://github.com/gabrielmagno/dracula-jupyterlab.git@feature/jupyterlab-4
```

**Comment by danielcs88** [comment]
Hi @gabrielmagno, I was able to install this commit! Thanks!

**Comment by ytdHuang** [comment]
@gabrielmagno 
Thank you for your hard work !
I've also installed this commit and it works very well.

This PR also fixes #23 #27 (which does the same thing in PR #39 )
Better to let the repo owner @karosc  merge it to master branch.

**Comment by karosc** [comment]
Thank you all for your hard work on this! I don't use jupyterlab really anymore. So if anyone wants to take over as owner of this repo and pypi project, I'd be happy to pass the torch. 

In the meantime, I was able to tag and release a new version on pypi after confirming the extension does install and work properly in jupyterlab 3 and 4

🚀 🔥 🙏🏻 
@gabrielmagno @danielcs88 @ytdHuang

**Pull request merged**
